moxy_path = "/moxy"
default_upstream = "http://localhost"
[[upstream]]
path_prefix = "/apps/basket"
url = "http://localhost:8085"
[[upstream]]
path_prefix = "/apps/browse"
url = "http://localhost:8085"
[[upstream]]
path_prefix = "/apps/details"
url = "http://localhost:8085"
[[upstream]]
path_prefix = "/apps/random"
url = "http://localhost:8085"