moxy_path = "/moxy"
default_upstream = "http://localhost:8081"
[[upstream]]
path_prefix = "/apps/basket"
host = "http://localhost:8085"
[[upstream]]
path_prefix = "/apps/browse"
host = "http://localhost:8085"
[[upstream]]
path_prefix = "/apps/details"
host = "http://localhost:8085"
[[upstream]]
path_prefix = "/apps/random"
host = "http://localhost:8085"